"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useState } from "react";
export default function AuthForm({ mode }: { mode: "signin" | "signup" }) {
  const router = useRouter(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(""); try { const endpoint = mode === "signup" ? "register" : "signin"; const response = await fetch(`/api/auth/${endpoint}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); router.push("/history"); } catch (e) { setError(e instanceof Error ? e.message : "Authentication failed."); } finally { setLoading(false); } }
  return <main className="mx-auto max-w-md px-6 py-20"><div className="rounded-[2rem] border border-slate-200 bg-white p-8 shadow-sm"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-cyan-600">JobPilot AI</p><h1 className="mt-3 text-3xl font-semibold">{mode === "signup" ? "Create your account" : "Welcome back"}</h1><form onSubmit={submit} className="mt-8 space-y-4"><input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="Email address" className="w-full rounded-xl border border-slate-200 px-4 py-3" /><input required minLength={8} type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Password (8+ characters)" className="w-full rounded-xl border border-slate-200 px-4 py-3" />{error && <p role="alert" className="text-sm text-red-600">{error}</p>}<button disabled={loading} className="w-full rounded-full bg-slate-900 px-4 py-3 font-semibold text-white">{loading ? "Please wait..." : mode === "signup" ? "Create account" : "Sign in"}</button></form><p className="mt-6 text-sm text-slate-500">{mode === "signup" ? "Already have an account? " : "New to JobPilot AI? "}<Link href={mode === "signup" ? "/signin" : "/signup"} className="font-semibold text-cyan-700">{mode === "signup" ? "Sign in" : "Create account"}</Link></p></div></main>;
}
